services:
  open-webui:
    image: ghcr.io/open-webui/open-webui@sha256:a6da0c292081d810a396ce786a10536d0b1b9ba2925dcca20ebb03f9fa90dbff
    container_name: open-webui
    init: true
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ENABLE_SIGNUP: "false"
      ENABLE_FOLLOW_UP_GENERATION: "false"
      ENABLE_TAGS_GENERATION: "false"
      ENABLE_TITLE_GENERATION: "false"
      CORS_ALLOW_ORIGIN: "http://192.168.0.66:3000;http://localhost:3000;http://127.0.0.1:3000"
      DO_NOT_TRACK: "true"
      SCARF_NO_ANALYTICS: "true"
      ANONYMIZED_TELEMETRY: "false"
    volumes:
      - open-webui:/app/backend/data
      - /etc/ullm/openwebui-secret-key:/app/backend/.webui_secret_key:ro
    networks:
      - open-webui-network

volumes:
  open-webui:
    external: true

networks:
  open-webui-network:
    external: true
